// <auto-generated />
using Galeria.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Galeria.Migrations
{
    [DbContext(typeof(GaleriaContext))]
    [Migration("20230601015421_Galeria")]
    partial class Galeria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Galeria.Models.Clientes", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Galeria.Models.GaleriaImg", b =>
                {
                    b.Property<int>("IdGaleriaImg")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdGaleriaImg");

                    b.ToTable("GaleriaImgs");
                });

            modelBuilder.Entity("Galeria.Models.Imagem", b =>
                {
                    b.Property<int>("IdImagem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdGaleria")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdImagem");

                    b.HasIndex("IdGaleria");

                    b.ToTable("Imagens");
                });

            modelBuilder.Entity("Galeria.Models.Imagem", b =>
                {
                    b.HasOne("Galeria.Models.GaleriaImg", "GaleriaImg")
                        .WithMany("Imagens")
                        .HasForeignKey("IdGaleria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GaleriaImg");
                });

            modelBuilder.Entity("Galeria.Models.GaleriaImg", b =>
                {
                    b.Navigation("Imagens");
                });
#pragma warning restore 612, 618
        }
    }
}
